# Read one line in the file generated by record_time.py
def load_time(filename):
    time_file = open(filename, "r")
    time = time_file.readline()
    time_file.close()
    return float(time)

# Write the header file, I've put it here as we don't need to parse XTML when reading the to_stream code
def write_header(header_file, sample_rate, t_now, t_utc, num_row):
    tab = "\t" # for readability
    header_file.write("<?xml version=\"1.0\" ?>\n")
    header_file.write("<stream ssi-v=\"2\">\n")
    header_file.write(tab + "<info ftype=\"ASCII\" sr=\"" + str(sample_rate) + "\" dim=\"1\" byte=\"4\" type=\"FLOAT\" delim=\";\" />\n")
    header_file.write(tab + "<meta />\n") # Not sure why we need this XML tag?
    header_file.write(tab + "<time ms=\"0\" local=\"" + t_now + "\" system=\"" + t_utc + "\"/>\n")
    header_file.write(tab + "<chunk from=\"0.000000\" to=\"" + str(num_row/sample_rate) + "\" byte=\"0\" num=\"" + str(num_row) + "\"/>\n")
    header_file.write("</stream>\n")