%Danielle Nadin 29-10-2019
%Source localization pipeline - automate source localization in
%Brainstorm from uploading .set file to exporting scout time series matrix
%for APCI analysis 

function [Value,Time,Atlas] = source_localize(pData,pCov,InverseMethod,template,bNorm)
    
    %% Variables
    % pData: INPUT, path to .set file
    % pCov: INPUT, path to the .set file used to compute the noise covariance matrix. If empty ([]), use the identity matrix. 
    % InverseMethod: INPUT, specify inverse model you will use (implemented options: MNE ('mne'), LCMV beamformer ('beamformer') )
    % template: INPUT, specify brain atlas you will use to cluster dipoles into ROIs (implemented options: Desikan-Killiany ('dk'), AAL('aal')
    % bNorm: INPUT, Boolean defining  whether you want to normalize the solution (for visualization, '1') or not (for connectivity analysis,'0')
    % Value: OUTPUT, structure containing the source time series
    % Time: OUTPUT, structure containing the time points associated with source time series
    % Atlas: OUTPUT, labels associated with each ROI in the chosen template
    
    %Input variable definition for testing
    pData = 'C:\Users\dn-xo\OneDrive - McGill University\Research\BIAPT Lab\Thesis\TDCS\Source localization\TDCS1_T2_baseline_NBACK.set';
    pCov = 'C:\Users\dn-xo\OneDrive - McGill University\Research\BIAPT Lab\Thesis\TDCS\Source localization\TDCS1_T2_baseline_EC.set';
    InverseMethod = 'mne';
    template = 'aal';
    bNorm = 0;
    
    %% Create protocol in Brainstorm
    ProtocolName = 'AutomateSourceLocalization';
    if ~brainstorm('status')
        brainstorm nogui 
    end
    
    gui_brainstorm('DeleteProtocol',ProtocolName);
    gui_brainstorm('CreateProtocol',ProtocolName,1,1); %Use default anatomy and one channel file per subject
    disp('Protocol created with default anatomy and channel locations.')
    
    sFiles = [];
    bst_report('Start',sFiles);
    sTemplate = struct('Name','Colin27_2016','FilePath','.\Colin27_2016.zip');
    db_set_template(0,sTemplate,0); %change default template to Colin27
    disp('Default anatomy changed to Colin27 template.')
    
    %% Process: Import data (pData, pCov)
    
    % ImportData
    db_add_subject('Subject',1,1,1); %subject id = 1
    sFiles = import_data(pData,[],'EEG-EEGLAB',[],1);
    disp('Imported EEG data.')
    
    %Import noise covariance data
    if ~isempty(pCov)
        db_add_subject('Noise Covariance',2,1,1); %subject id = 2
        sNoise = import_data(pCov,[],'EEG-EEGLAB',[],2);
        
        sNoise = bst_process('CallProcess', 'process_channel_addloc', sNoise, [], ...
            'usedefault',  30, ...  % Colin27: GSN HydroCel 128 E1
            'fixunits',    1, ...
            'vox2ras',     1);
    end
    disp('Imported noise covariance data.')
    %TODO: deal with pop-ups + don't import channel file when you import data
    
    %Project electrodes to the scalp surface
    %sFiles = bst_process('CallProcess', 'process_channel_project', sFiles, []);
    sFiles = bst_process('CallProcess', 'process_channel_addloc', sFiles, [], ...
    'usedefault',  30, ...  % Colin27: GSN HydroCel 128 E1
    'fixunits',    1, ...
    'vox2ras',     1);

    
    %% Process: Compute head model
  
    %Cortex head model: there are 2 dipoles not inside the skull - Edit cortical surface -
    %force inside the inner skull
    db_path =  bst_get('BrainstormDbDir');
    tess_force_envelope([db_path '\' ProtocolName '\anat\@default_subject\tess_cortex_pial_low.mat'],...
        [db_path '\' ProtocolName '\anat\@default_subject\tess_innerskull.mat']);
    disp('Forced dipoles inside skull.')
    %TODO: Volume head model: there are 86 dipoles not inside the grey matter??
    if strcmp('dk',template) %DK atlas: cortex head model
        sFiles = bst_process('CallProcess', 'process_headmodel', sFiles, [], ...
            'sourcespace', 1, ...  % Cortex surface
            'eeg',         3, ...  % OpenMEEG BEM
            'openmeeg',    struct(... %default
                'BemSelect',    [1, 1, 1], ...
                'BemCond',      [1, 0.0125, 1], ...
                'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
                'BemFiles',     {{}}, ...
                'isAdjoint',    0, ...
                'isAdaptative', 1, ...
                'isSplit',      0, ...
                'SplitLength',  4000));
        disp('Computed cortex head model.')
    elseif strcmp('aal',template) % AAL atlas: volume head model
        sFiles = bst_process('CallProcess', 'process_headmodel', sFiles, [], ...
            'sourcespace', 2, ...  % MRI volume
            'volumegrid',  struct(... %default
                'Method',        'adaptive', ...
                'nLayers',       17, ...
                'Reduction',     3, ...
                'nVerticesInit', 4000, ...
                'Resolution',    0.005, ...
                'FileName',      []), ...
            'eeg',         3, ...  % OpenMEEG BEM
            'openmeeg',    struct(... %default
                'BemFiles',     {{}}, ...
                'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
                'BemCond',      [1, 0.0125, 1], ...
                'BemSelect',    [1, 1, 1], ...
                'isAdjoint',    0, ...
                'isAdaptative', 1, ...
                'isSplit',      0, ...
                'SplitLength',  4000));
            disp('Computed volume head model.')
    end
         
    %% Process: Compute noise covariance
    if ~isempty(pCov)
        %Compute noise covariance matrix
        sNoise = bst_process('CallProcess', 'process_noisecov', sNoise, [], ...
            'target',         1, ...  % Noise covariance     (covariance over baseline time window)
            'dcoffset',       1, ...  % Block by block, to avoid effects of slow shifts in data
            'identity',       0, ...
            'copycond',       0, ...
            'copysubj',       0, ...
            'copymatch',      0, ...
            'replacefile',    1);  % Replace
        disp('Computed noise covariance matrix.')
        db_set_noisecov(5,'AllSubjects'); %i = 5 is the index of the study containing the noise cov matrix
        disp('Copied noise covariance matrix to Subject.')
    else
        %Use identity matrix, no noise modelling
        sFiles = bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
            'target',         1, ...  % Noise covariance     (covariance over baseline time window)
            'dcoffset',       1, ...  % Block by block, to avoid effects of slow shifts in data
            'identity',       1, ...
            'copycond',       0, ...
            'copysubj',       0, ...
            'copymatch',      0, ...
            'replacefile',    1);  % Replace
        disp('Using identity matrix for noise modelling.')
    end
    %% Process: Compute inverse solution
    
    if strcmp('mne',InverseMethod) && strcmp('dk',template) && strcmp(1,bNorm)
            sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
                'output',  2, ...  % Kernel only: one per file
                'inverse', struct(...
                'Comment',        'dSPM-unscaled: EEG', ...
                'InverseMethod',  'minnorm', ...
                'InverseMeasure', 'dspm2018', ...
                'SourceOrient',   {{'fixed'}}, ...
                'NoiseMethod',    'diag', ...
                'DataTypes',      {{'EEG'}}));
            disp('Computed inverse solution.')
    elseif strcmp('mne',InverseMethod) && strcmp('dk',template) && strcmp(0,bNorm)
            sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
                'output',  2, ...  % Kernel only: one per file
                'inverse', struct(...
                'Comment',        'MN: EEG', ...
                'InverseMethod',  'minnorm', ...
                'InverseMeasure', 'amplitude', ...
                'SourceOrient',   {{'fixed'}}, ...
                'NoiseMethod',    'diag', ...
                'DataTypes',      {{'EEG'}}));
            disp('Computed inverse solution.')
    elseif strcmp('mne',InverseMethod) && strcmp('aal',template) && strcmp(1,bNorm)
        sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
                'output',  2, ...  % Kernel only: one per file
                'inverse', struct(...
                'Comment',        'dSPM-unscaled: EEG', ...
                'InverseMethod',  'minnorm', ...
                'InverseMeasure', 'dspm2018', ...
                'SourceOrient',   {{'free'}}, ...
                'NoiseMethod',    'diag', ...
                'DataTypes',      {{'EEG'}}));
            disp('Computed inverse solution.')
    elseif strcmp('mne',InverseMethod) && strcmp('aal',template) && strcmp(0,bNorm)
        sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
                'output',  2, ...  % Kernel only: one per file
                'inverse', struct(...
                'Comment',        'MN: EEG', ...
                'InverseMethod',  'minnorm', ...
                'InverseMeasure', 'amplitude', ...
                'SourceOrient',   {{'free'}}, ...
                'NoiseMethod',    'diag', ...
                'DataTypes',      {{'EEG'}}));
            disp('Computed inverse solution.')
    elseif strcmp('beamformer',InverseMethod) && strcmp('dk',template)
        sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
            'output',  2, ...  % Kernel only: one per file
            'inverse', struct(...
            'Comment',        'PNAI: EEG', ...
            'InverseMethod',  'lcmv', ...
            'InverseMeasure', 'nai', ...
            'SourceOrient',   {{'fixed'}}, ...
            'NoiseMethod',    'diag', ...
            'DataTypes',      {{'EEG'}}));
        disp('Computed inverse solution.')
    elseif strcmp('beamformer',InverseMethod) && strcmp('aal',template)
        sFiles = bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
            'output',  2, ...  % Kernel only: one per file
            'inverse', struct(...
            'Comment',        'PNAI: EEG', ...
            'InverseMethod',  'lcmv', ...
            'InverseMeasure', 'nai', ...
            'SourceOrient',   {{'free'}}, ...
            'NoiseMethod',    'diag', ...
            'DataTypes',      {{'EEG'}}));
        disp('Computed inverse solution.')
    elseif strcmp('wmem',InverseMethod)
        disp('TODO: implement wMEM')
    end
    %%  Process: Compute time series in ROIs
  
    if strcmp('dk',template)
        sFiles = bst_process('CallProcess', 'process_extract_scout', sFiles, [], ...
            'scouts',         {'Desikan-Killiany', {'bankssts L', 'bankssts R', 'caudalanteriorcingulate L', 'caudalanteriorcingulate R', 'caudalmiddlefrontal L', 'caudalmiddlefrontal R', 'cuneus L', 'cuneus R', 'entorhinal L', 'entorhinal R', 'frontalpole L', 'frontalpole R', 'fusiform L', 'fusiform R', 'inferiorparietal L', 'inferiorparietal R', 'inferiortemporal L', 'inferiortemporal R', 'insula L', 'insula R', 'isthmuscingulate L', 'isthmuscingulate R', 'lateraloccipital L', 'lateraloccipital R', 'lateralorbitofrontal L', 'lateralorbitofrontal R', 'lingual L', 'lingual R', 'medialorbitofrontal L', 'medialorbitofrontal R', 'middletemporal L', 'middletemporal R', 'paracentral L', 'paracentral R', 'parahippocampal L', 'parahippocampal R', 'parsopercularis L', 'parsopercularis R', 'parsorbitalis L', 'parsorbitalis R', 'parstriangularis L', 'parstriangularis R', 'pericalcarine L', 'pericalcarine R', 'postcentral L', 'postcentral R', 'posteriorcingulate L', 'posteriorcingulate R', 'precentral L', 'precentral R', 'precuneus L', 'precuneus R', 'rostralanteriorcingulate L', 'rostralanteriorcingulate R', 'rostralmiddlefrontal L', 'rostralmiddlefrontal R', 'superiorfrontal L', 'superiorfrontal R', 'superiorparietal L', 'superiorparietal R', 'superiortemporal L', 'superiortemporal R', 'supramarginal L', 'supramarginal R', 'temporalpole L', 'temporalpole R', 'transversetemporal L', 'transversetemporal R'}}, ...
            'scoutfunc',      1, ...  % Mean
            'isflip',         1, ...
            'isnorm',         1, ...
            'concatenate',    1, ...
            'save',           1, ...
            'addrowcomment',  1, ...
            'addfilecomment', 1);
        disp('Computed Desikan-Killiany atlas-based timeseries.')
    elseif strcmp('aal',template)
        %import AAL atlas
        import_label([db_path '\' ProtocolName '\anat\@default_subject\subjectimage_T1.mat'],'./aal_for_SPM12/ROI_MNI_V4.nii');
        disp('Imported AAL atlas.')
        %extract time series
        sFiles = bst_process('CallProcess', 'process_extract_scout', sFiles, [], ...
            'timewindow',     [], ...
            'scouts',         {'Volume 15212: ROI_MNI_V4', {'2001', '2002', '2101', '2102', '2111', '2112', '2201', '2202', '2211', '2212', '2301', '2302', '2311', '2312', '2321', '2322', '2331', '2332', '2401', '2402', '2501', '2502', '2601', '2602', '2611', '2612', '2701', '2702', '3001', '3002', '4001', '4002', '4011', '4012', '4021', '4022', '4101', '4102', '4111', '4112', '4201', '4202', '5001', '5002', '5011', '5012', '5021', '5022', '5101', '5102', '5201', '5202', '5301', '5302', '5401', '5402', '6001', '6002', '6101', '6102', '6201', '6202', '6211', '6212', '6221', '6222', '6301', '6302', '6401', '6402', '7001', '7002', '7011', '7012', '7021', '7022', '7101', '7102', '8101', '8102', '8111', '8112', '8121', '8122', '8201', '8202', '8211', '8212', '8301', '8302', '9001', '9002', '9022', '9031', '9032', '9041', '9042', '9120', '9130'}}, ...
            'scoutfunc',      1, ...  % Mean
            'isflip',         1, ...
            'isnorm',         1, ...
            'concatenate',    1, ...
            'save',           1, ...
            'addrowcomment',  1, ...
            'addfilecomment', 1);
        disp('Computed AAL atlas-based timeseries.')
    end
  
    %% Process: Load output file to populate output variables
    load([db_path '\' ProtocolName '\data\' sFiles.FileName])
end